[package]
name = "bign-handheld-thumbnailer"
version = "0.1.0"
authors = ["Mateus Rodrigues Costa <mateusrodcosta@gmail.com>"]
edition = "2021"
description = "A thumbnailer for Nintendo handheld systems (Nintendo DS and 3DS) roms and files"
readme = "README.md"
repository = "https://github.com/MateusRodCosta/bign-handheld-thumbnailer"
license = "GPL-2.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
gio = "0.19.2"
glib = "0.19.2"
gdk-pixbuf = "0.19.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
