[package]
name = "bign-handheld-thumbnailer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.19.2"
gdk-pixbuf = "0.19.2"
clap = { version = "4.0", features = ["derive"] }
rgb565 = "0.1.3"

[profile.release]
strip = true
lto = true
